/**
 * Founder Story — chapter content.
 *
 * Source: "KIPLANScholar_About_Page_Final_Editorial_Pass.docx"
 * (approved editorial manuscript, 12 August 2026).
 *
 * Content here is reproduced verbatim from the approved manuscript.
 * The only changes made are technical formatting fixes introduced by
 * the .docx → text conversion (restoring em dashes and apostrophes
 * that were escaped in the source conversion, and representing
 * paragraph breaks as array entries). No wording, meaning, fact, or
 * chronology has been altered, shortened, or reinterpreted.
 *
 * Do not edit this file's prose without an updated approved manuscript.
 *
 * Images below are imported from src/assets/images/ (not the public/
 * folder) — these are genuine ES module imports, resolved and
 * hashed by Vite at build time, not runtime string paths.
 */

import earlyLife from "../assets/images/01_EarlyLife.jpg";
import umnCareer from "../assets/images/04_UMN_Career.jpeg";
import endeavourAward from "../assets/images/08_Endeavour_Award.jpg";
import uniCanverra from "../assets/images/05_uni_canverra.jfif";
import convDavies from "../assets/images/07_Conv1_Davies.jpeg";
import convMonikaKennedy from "../assets/images/08_Con2_MonikaKennedy.jpeg";
import returnToNepal from "../assets/images/10_Return.jpg";
import aiImage from "../assets/images/13_AIImage.webp";

export interface ChapterImage {
  src: string;
  alt: string;
}

export interface FounderChapter {
  number: number;
  title: string;
  /** 5–7 sentence preview shown before "Read more" is clicked. */
  preview: string;
  /** Full chapter text, one paragraph per array entry. */
  fullText: string[];
  /**
   * One or more images for this chapter. A single entry renders as
   * the standard hero-style two-column layout; multiple entries
   * (currently only Chapter 9) render as a primary image with a
   * small supporting gallery alongside it.
   */
  images?: ChapterImage[];
  /** Which side the image column sits on, desktop only. Defaults to "left". */
  imageSide?: "left" | "right";
}

export const FOUNDER_CHAPTERS: FounderChapter[] = [
  {
    number: 1,
    title: "Where the Journey Began",
    preview:
      "I was born and raised in a remote part of Bhojpur District, Nepal, at a time when opportunities were very different from today. Thanks to the technology we have today, hundreds of thousands of people can discover opportunities that once seemed almost impossible to find; I often think about how different my own journey would have been if such technology had existed then. I was the eldest son among seven children, and my parents placed great trust in me. In 1985, I left home for Kathmandu with encouragement from my mother, some money she had saved secretly, and the responsibility of being the first child to move ahead. That journey began with two days of walking before I reached Hile, where I saw a road and a bus for the first time. I had read about Kathmandu in books, but seeing the capital city in real life was a completely different experience.",
    fullText: [
      "I was born and raised in a remote area of Bhojpur District, Nepal. My childhood was shaped by a simple family environment, limited resources and the strong expectation that education could open a better future. I was the eldest son among seven children, so I understood early that my decisions would also influence those who came after me.",
      "In 1985, I came to Kathmandu with the encouragement of my mother. Her message was simple: go, work hard and achieve what you want. She had saved some money secretly for my journey. That small amount was enough to begin the trip, but the confidence and trust she gave me were worth much more.",
      "The journey itself is one of my earliest lasting memories. I walked for two days to reach Hile, one of the first places where I saw a road in the hill region. I saw a bus for the first time and thought it looked almost like a house with wheels. The following day, I continued towards Kathmandu.",
      "I had read about Kathmandu in books and knew that it was the capital of Nepal. But reading about a place and actually seeing it are two very different things. Arriving in Kathmandu was the beginning of a new chapter in my life — a chapter that would eventually take me much farther than I could have imagined.",
    ],
    images: [{ src: earlyLife, alt: "Early life in Bhojpur District, Nepal" }],
    imageSide: "left",
  },
  {
    number: 2,
    title: "Learning While Earning",
    preview:
      "My college years were shaped by the practical need to earn a living while continuing my education. I attended college in a morning or evening shift so that I could work around my studies. In those days, communication was also very different from what young people experience today. Wireless communication was used for urgent messages, and a letter sent by post from Kathmandu to my home in Dingla could take around twenty days. These limitations made every opportunity harder to discover and every important message more valuable. Looking back, I realize that the discipline of studying while earning became one of the foundations of my later professional life.",
    fullText: [
      "My college life was not simply a period of study. It was also a period of learning how to manage responsibility. I needed to earn for my living, so I attended college in a morning or evening shift depending on what work required.",
      "The communication environment of those days was very different. Wireless communication was used when something was urgent, and ordinary communication by post was slow. A letter travelling from Kathmandu to Dingla, my home, could take around twenty days. There were no mobile phones, email or instant messaging to bridge that distance.",
      "Those conditions taught me patience. They also taught me that access to information can change the direction of a person's life. Today, a student can search, compare, communicate and apply from a mobile phone. At that time, finding the right information often depended on newspapers, personal contacts, letters and persistence.",
      "I completed my Bachelor's degree in 1992. By then, I had already learned an important lesson: education is not only something that happens inside a classroom. It is a continuous effort to improve one's circumstances and create possibilities for oneself and one's family.",
    ],
  },
  {
    number: 3,
    title: "First Job, Jajarkot and the Path to HR",
    preview:
      "After completing my Bachelor's degree, I chose to work in one of Nepal's most remote districts, Jajarkot. Through United Mission to Nepal (UMN), I was trained and deployed there, and receiving my first salary was a very happy moment. I could finally contribute to my family, and I especially wanted to support the education of my younger brother and sisters. At the same time, I continued my own education. During this period, I attended the morning shift at campus and was also able to complete my Master's degree in Business Administration. The experience taught me that professional responsibility and education could progress together when there was a clear purpose.",
    fullText: [
      "After completing my Bachelor's degree in 1992, I decided to serve in Jajarkot, one of the most remote districts of Nepal. United Mission to Nepal (UMN) trained and deployed me there. It was my first professional job and the first time I received a regular monthly salary.",
      "That first salary was a very happy moment. It was not only income for myself; it gave me the opportunity to support my family. I had a personal reason for choosing a remote posting: the remuneration allowed me to help my younger brother and sisters continue their education in Kathmandu. Eventually, I was able to help all of them continue their studies.",
      "At the same time, I did not stop my own education. During this period, I attended the morning shift at campus and was also able to complete my Master's degree in Business Administration. Balancing employment, study and family responsibility was demanding, but it became an important part of my professional character.",
      "Those years in Jajarkot also gave me a deeper understanding of Nepal beyond Kathmandu. Working in a remote district made me appreciate how geography, information and opportunity can shape people's lives.",
    ],
  },
  {
    number: 4,
    title: "UMN Headquarters and the HR Profession",
    preview:
      "Around 1996, the Maoist insurgency affected life across Nepal, including the region where I was working, and I was compelled to move to UMN Headquarters in Kathmandu. UMN was a large and diverse organization, working across education, health, rural development and engineering projects. I was assigned as a Personnel Officer and gradually moved deeper into human resources work. I learned from colleagues and supervisors who treated professional development as something worth investing in. Two people remain especially important in my memory: Ann McKonkey, whom we called Didee, and S. R. Ranjit, whom we called Dai. Their kindness, encouragement and guidance became invaluable to my career, and I remain grateful to them.",
    fullText: [
      "Around 1996, the Maoist insurgency affected everyone in Nepal, including the region where I was working. Circumstances compelled me to return to UMN Headquarters in Kathmandu.",
      "UMN was a diverse organization with projects in education, health, rural development, industrial and engineering fields across Nepal. It employed a large number of Nepali staff and expatriate professionals and was one of the significant sources of employment outside government service.",
      "At headquarters, I was assigned as a Personnel Officer. This became an important turning point in my professional life because I began to work more deeply in human resources management, personnel policy and organizational systems.",
      "I was fortunate to work with people who supported my development. Ann McKonkey — whom we called Didee in the office — and S. R. Ranjit — whom we called Dai — were especially important to me. Thank you, Didee and Dai. Your kindness and encouragement have been invaluable to my career, and I wish you both good health.",
      "The lessons I learned during this period eventually became part of the professional foundation I carry today as an HRM specialist.",
    ],
    images: [{ src: umnCareer, alt: "United Mission to Nepal (UMN) Personnel team" }],
    imageSide: "right",
  },
  {
    number: 5,
    title: "Change, Uncertainty and the Decision to Explore",
    preview:
      "The world around UMN was changing, and those changes eventually reached the organization itself. Localization and Nepalisation brought major organizational restructuring, including new statutes, policies, regulations and recruitment systems. Layoffs, strikes and uncertainty made the future difficult to predict. Instead of simply waiting for circumstances to decide my future, I began looking for new opportunities. I started reading English newspapers every day and collecting information about vacancies and educational opportunities. That habit became the bridge between uncertainty and the international scholarship journey that followed.",
    fullText: [
      "The world was changing rapidly, and organizations in Nepal were changing with it. The broader changes associated with the end of the Cold War and the growing emphasis on localization also affected UMN.",
      "Projects were being transferred, local organizations were emerging, and the organization entered a transition period involving new statutes, policies, regulations and systems. Around 2005, layoffs, strikes and even hunger strikes became part of an environment I had never expected to experience.",
      "The situation created uncertainty, but it also forced me to think differently. I decided that I should not simply wait for circumstances to determine my future.",
      "I began reading English newspapers every day. I collected vacancy notices and information about new opportunities. At first, this was simply a practical response to uncertainty. Gradually, it became a habit of searching for possibilities beyond the immediate circumstances around me.",
      "That habit would eventually lead me to discover an opportunity for higher education — and change the direction of my life.",
    ],
  },
  {
    number: 6,
    title: "Discovering the Door to International Education",
    preview:
      "One day I found an advertisement for an international higher-education opportunity — an ALA Award — with a deadline of only two months. Two months sounded sufficient, but the reality of preparing documents was very different. University verification, line-ministry verification, passport preparation, IELTS preparation and examinations all required time and coordination. I missed that deadline, and a year passed. Instead of giving up, I decided that IELTS would be the first door I needed to open for future international opportunities. I prepared from the beginning of the next cycle, secured the required score and continued searching after office hours. The experience taught me that opportunities are often lost not because people lack ability, but because they do not know where to find them or what to prepare.",
    fullText: [
      "One day, while reading the newspaper, I found an opportunity for higher education — an ALA Award. The deadline was two months away. Under normal circumstances, two months might seem like enough time, but I soon learned how much preparation an international application could require.",
      "University verification, line-ministry verification, passport preparation, IELTS preparation, examinations and other documents all had to be managed. By the time I understood what was required, the deadline had passed. One year was gone.",
      "But I did not consider the experience a failure. I learned from it. I decided that IELTS was one of the important doors I needed to open for future international opportunities, so I prepared from the beginning of the next cycle.",
      "I succeeded in obtaining an internationally acceptable IELTS band. From then onward, searching for opportunities and preparing documents became part of my routine after office hours.",
      "This was one of the most important lessons of my life: sometimes a person does not miss an opportunity because of lack of talent. The opportunity may simply be difficult to find, difficult to understand, or difficult to prepare for within the available time.",
    ],
  },
  {
    number: 7,
    title: "The People Who Encouraged Me",
    preview:
      "My scholarship journey was never mine alone. Along the way, I met people who encouraged me, answered questions and gave me confidence when I needed it. Ann McKonkey — Didee — and S. R. Ranjit — Dai — were among those people who supported my professional development and encouraged me during important stages of my career. Their kindness reminded me that one person's guidance can influence another person's future for many years. I carry that lesson with me today. KIPLANScholar is also built on the belief that useful information, encouragement and practical guidance can make a difficult journey easier.",
    fullText: [
      "Looking back, I know that my journey was supported by many people. Some gave formal professional guidance; others offered encouragement at exactly the moment it was needed.",
      "Ann McKonkey — Didee — and S. R. Ranjit — Dai — hold a special place in that memory. Their kindness and encouragement helped me through important stages of my professional development.",
      "Thank you, Didee and Dai. Your kindness is invaluable to my career, and I wish you good health.",
      "This is also one reason I value the human side of opportunity. Information is important, but encouragement matters too. A person who is uncertain about applying for a scholarship may need only one useful piece of information, one supportive person or one clear explanation to decide to continue.",
      "That understanding has stayed with me throughout my career and has influenced the way I think about KIPLANScholar.",
    ],
  },
  {
    number: 8,
    title: "The Endeavour Award",
    preview:
      "Eventually, the opportunity I had been searching for arrived. I was nominated by the Federal Government of Australia for postgraduate study for two years. It was a moment of great happiness, but it was also a moment of preparation and responsibility. I spent time meeting friends, relatives and family before leaving Nepal. I submitted my resignation, although my employer did not accept it, and then left for Australia. The journey from Nepal to Australia was itself an unforgettable experience. I was going to study, but I was also beginning a life experience that would change the way I understood education, work and international opportunity.",
    fullText: [
      "Finally, the day I had been waiting for arrived. I was nominated by the Federal Government of Australia for higher education for two years through the Australian Government Endeavour Award.",
      "Before leaving, I tried to meet as many friends, relatives and family members as possible within a short period. I submitted my resignation to my employer, but it was not accepted. I nevertheless left for Australia to pursue the opportunity.",
      "The journey itself remains vivid in my memory. I flew late at night, reached Hong Kong early in the morning and continued towards Australia. In Sydney, a friend arranged for me to stay with relatives.",
      "I also remember the difference in climate. I had left Kathmandu during a cold period, carrying my heavy winter coat, and arrived in Sydney where it was warm. My coat suddenly became almost useless.",
      "These small memories remain meaningful because the scholarship was not simply a study opportunity. It was the beginning of a major personal and professional transformation.",
    ],
    images: [{ src: endeavourAward, alt: "Kamal Khadka holding the Australian Government Endeavour Award, 2009–2010, at the University of Canberra" }],
    imageSide: "left",
  },
  {
    number: 9,
    title: "Canberra and a World of New Learning",
    preview:
      "Arriving at the University of Canberra opened another world for me. During orientation, I discovered an educational environment where undergraduate, graduate and master's students could be part of the same academic setting. I met people from many countries and developed friendships that remain part of my memories, including a particularly helpful friend from Lahore, Pakistan. My family later joined me, and together we spent more than two years in Canberra. Living and studying in Australia's federal capital changed my understanding of education, culture and professional life. It showed me what becomes possible when a person receives the right opportunity and is prepared to work for it.",
    fullText: [
      "When I arrived at the university, I attended the orientation programme and experienced a learning environment very different from what I had known in Nepal.",
      "One of the interesting things I noticed was that undergraduate, graduate and master's students could be part of the same academic environment. Later, I understood that students at different levels were also expected to complete assignments and examinations appropriate to their programmes.",
      "I made friends from many parts of the world. One friend from Lahore, Pakistan, was particularly helpful throughout my studies, and I remain grateful for that friendship.",
      "Eventually, my family joined me. My wife made the difficult decision to sacrifice her job, and my son also had to leave St. Xavier's school so that we could spend this period together in Australia.",
      "We lived in the Australian Capital Territory, Canberra, for more than two years. Those years became some of the most valuable years of my life — academically, professionally and personally.",
    ],
    images: [
      { src: uniCanverra, alt: "University of Canberra" },
      { src: convDavies, alt: "Convocation photograph with Doug Davies" },
      { src: convMonikaKennedy, alt: "Convocation photograph with Monika Kennedy" },
    ],
    imageSide: "right",
  },
  {
    number: 10,
    title: "Returning to Nepal With New Knowledge",
    preview:
      "After completing my studies, I made a conscious decision to return to Nepal and apply what I had learned in Australia to Nepal's development. Returning home did not mean returning to the same place; I came back with new knowledge, new perspectives and a broader understanding of institutions and people. UMN again offered me a Personnel Advisor position, and I continued my professional journey. Later, I accepted an international assignment with Liverpool Associates in Tropical Health (LATH), associated with the University of Liverpool, London. I was deployed to the Ministry of Health and Population as a Technical Advisor / National HRH Officer. These experiences allowed me to connect international knowledge with Nepal's practical institutional needs.",
    fullText: [
      "Upon completion of my studies, I made a conscious decision to return to Nepal and apply the knowledge, skills and perspectives I had acquired in Australia to contribute to Nepal's development.",
      "UMN again offered me a Personnel Advisor position, and I continued working there for about another year and a half. After that, I decided to take an international assignment.",
      "I joined Liverpool Associates in Tropical Health (LATH), associated with the University of Liverpool, London. Through that work, I was deployed to the Ministry of Health and Population as a Technical Advisor / National HRH Officer.",
      "This period gave me an opportunity to connect international professional practice with Nepal's health-sector human resources needs. It was also a reminder that international education becomes most meaningful when knowledge can be brought home and applied to real problems.",
      "My professional journey continued through senior advisory, management and professional roles involving human resources, policy, institutional reform and capacity development.",
    ],
    images: [{ src: returnToNepal, alt: "Returning to Nepal after completing studies in Australia" }],
    imageSide: "left",
  },
  {
    number: 11,
    title: "Contributing to Nepal's Health Workforce",
    preview:
      "One of the important areas of my professional work was human resources for health. I contributed to national workforce planning, policy consultation and institutional development in collaboration with government ministries, technical experts and development partners. I served as a Technical Advisor / National HRH Officer and participated in processes involving the Ministry of Health and Population and international partners. I contributed to the preparation of Nepal's Country Profile and the Twenty-Year Human Resources for Health Workforce Plan. The work required extensive coordination, survey design and data monitoring across Nepal, but the lasting value for me was understanding how evidence, planning and people come together in national development. I carry that experience into my current work and thinking.",
    fullText: [
      "My professional experience after returning to Nepal included work in human resources for health, workforce planning, policy consultation, institutional reform and capacity development.",
      "As a Technical Advisor / National HRH Officer, I worked with government institutions, technical experts and development partners. One significant contribution was participation in the preparation of Nepal's Country Profile and the Twenty-Year Human Resources for Health Workforce Plan.",
      "The work involved collaboration across institutions and required careful attention to evidence and data. I was involved in survey design and data monitoring across Nepal, working with people and institutions in different settings.",
      "I do not present this part of my history to claim a single-person achievement. National work is always a collective effort. My contribution was one part of a larger team involving government, technical experts, development partners and international organizations.",
      "What I gained from the experience was a deeper understanding of how information, planning, people and institutions must work together if a national programme is to succeed.",
    ],
  },
  {
    number: 12,
    title: "A Career Built Around People, Systems and Learning",
    preview:
      "Across my career, my work has remained connected to people, organizations and systems. I have advised public, private and non-governmental institutions on governance, organizational development and strategic management. I have participated in policy consultations and worked with international organizations, development partners and foreign experts working in Nepal. My international exposure includes postgraduate study in Australia through the University of Canberra and the Australian Government Endeavour Award, as well as collaboration with UK-linked development work. These experiences strengthened my belief that professional knowledge is most valuable when it is shared and applied. They also shaped the way I now approach education, opportunity and technology.",
    fullText: [
      "Since returning to Nepal, I have served in senior advisory, management and professional roles and have contributed to areas including policy initiatives, institutional reform, workforce planning, governance strengthening, organizational development and capacity building.",
      "I have worked with public, private and non-governmental institutions and developed long-standing professional relationships with international organizations, development partners and foreign experts working in Nepal.",
      "My international exposure includes postgraduate study and professional engagement in Australia through the University of Canberra and the Australian Government Endeavour Award, as well as collaboration with UK-linked development work through Liverpool Associates in Tropical Health.",
      "These experiences have given me a broad perspective. I have seen organizations from the perspective of people, systems, policy and management. I have also seen how access to knowledge and opportunity can influence an individual's professional and personal life.",
      "That combination of experience is part of the foundation behind my current identity as an AI Practitioner | HRM Specialist.",
    ],
  },
  {
    number: 13,
    title: "Discovering AI Later in Life",
    preview:
      "Much later in my career, another major wave of change arrived: artificial intelligence. I began taking AI training through online resources and YouTube and initially found the technology challenging. Instead of treating that challenge as something to avoid, I decided to learn and experiment with it. In a stage of life when many people might slow down, I found myself enjoying a new area of learning. AI has the potential to reduce barriers to information, learning and productivity for people who use it responsibly. That is one reason I now want to share what I learn and help others understand how technology can benefit them.",
    fullText: [
      "In recent years, I have encountered another major transformation: artificial intelligence.",
      "I began learning through online training, practical experimentation and YouTube. It was challenging. Technology can be intimidating when it changes quickly, and AI is certainly changing quickly.",
      "But I decided to learn rather than step away from it. In this stage of my life, I have actually enjoyed the process.",
      "I believe AI will become part of everyday life for almost everyone. It may change the way people work, learn, communicate and solve problems. Used responsibly, it can help people access information and accomplish tasks that once required considerable time and resources.",
      "For me, becoming an AI Practitioner is not about claiming that technology can replace people. It is about learning how technology can help people — especially people who have limited access to information, guidance or professional resources.",
    ],
    images: [{ src: aiImage, alt: "Kamal Khadka's AI journey" }],
    imageSide: "right",
  },
  {
    number: 14,
    title: "Why I Built KIPLANScholar",
    preview:
      "My own scholarship journey showed me how difficult it can be to find an opportunity, understand its requirements and prepare the necessary documents. Today, technology makes it possible to bring reliable information much closer to students. KIPLANScholar is my attempt to use that possibility to help talented Nepali students, professionals and entrepreneurs discover international education and scholarship opportunities. The platform is intended to reduce the need to search dozens of websites at the wrong time or rely only on informal information from friends. It brings opportunities, preparation resources and practical tools into one place. It is not a promise of success; it is an attempt to make the path clearer and more manageable.",
    fullText: [
      "This long story carries a particular purpose.",
      "I know from my own experience how difficult it can be to find one international opportunity, understand the requirements, prepare documents, meet deadlines and keep going when the first attempt does not work.",
      "Today, technology gives us an opportunity that did not exist when I began my journey. A student can use a mobile phone to search for information, compare opportunities, prepare documents and receive updates.",
      "That is the idea behind KIPLANScholar.",
      "As an AI Practitioner | HRM Specialist, I decided to establish this student portal to share and explore an easier way to find information about international education and scholarship opportunities.",
      "My hope is that talented students, professionals and entrepreneurs will not miss an opportunity simply because they do not know where to find it or what they need to prepare.",
      "KIPLANScholar will improve gradually. It is an ongoing effort, not a finished promise.",
    ],
  },
  {
    number: 15,
    title: "A Dream for Nepali Students and Professionals",
    preview:
      "My hope is simple: that hundreds of talented Nepali students and professionals will benefit from the opportunities they discover through KIPLANScholar. I would like the platform to become a useful place for fresh graduates, working professionals, women professionals, entrepreneurs and others who are looking for reliable educational opportunities. The platform is designed to grow over time, with more scholarships, skills opportunities and preparation resources added gradually. Students should be able to use a mobile phone, register an email account, receive updates, prepare documents and keep track of their application progress. I do not promise that every visitor will receive a scholarship; I want to help people become better informed and better prepared. If even one person's life, family or community is improved because they found an opportunity here, the effort will have meaning.",
    fullText: [
      "My dream is not to promise a scholarship to everyone. My dream is to help hundreds of talented Nepali students and professionals find opportunities that they might otherwise miss.",
      "I want KIPLANScholar to be useful to fresh graduates, students from different educational backgrounds, working professionals, professional women, entrepreneurs and anyone who is seriously looking for international education or scholarship opportunities.",
      "The platform will continue to grow. New opportunities can open, existing opportunities can close, and new resources can be added. The intention is to keep the information useful and current rather than treating the website as a static collection of pages.",
      "A student should not need an expensive computer or a complicated system just to begin. A mobile phone should be enough to visit the platform, register an email account, receive updates, prepare a professional or academic CV, work on a Statement of Purpose, prepare a Letter of Recommendation and keep documents available for future use.",
      "The platform is also intended to help users track their progress — submission, interview, success, or another attempt in a future year.",
      "I know that information alone does not create success. The student still needs discipline, preparation, persistence and hard work.",
      "But reliable information at the right time can open a door.",
      "That is what I hope KIPLANScholar will do.",
    ],
  },
];